Fix BluetoothOppIncomingFileActivityTest
File & class name was too long, which caused NoClassDefFoundError

Change-Id: Iab8dec57851735117167675f381b146d7d3191e3
Test: atest BluetoothInstrumentionTests
Bug: 237467631
Tag: #refactor