Revert "Clean up correct state machine"
This reverts commit 4c33e9fb9443e117116cf5e1caa15f5277555fce.

Reason for revert: b/312448477 test breakage
```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Looper android.os.Handler.getLooper()' on a null object reference
	at com.android.bluetooth.mapclient.MapClientServiceTest.disconnect_doesNotCleanUpNewStateMachineOfSameDevice(MapClientServiceTest.java:264)
```

Bug: 312448477
Change-Id: Idb4265bed8412224f2c4cec4393e742cf7ee73ac