Alias iterator in packet-gen
The msvc compiler is unable to translate some of the generated code:

error: no viable conversion from 'std::array<uint8_t, 248>::iterator'
(aka '_Array_iterator<unsigned char, 248ULL>') to 'uint8_t *' (aka
'unsigned char *')

Instead of assigning the value to a ptr, we alias the iterator instead.

Test: atest bluetooth_test_gd
Tag: #gd-refactor
Bug: 182505215
Change-Id: I389b26d71ef5bd8f96ae819d34ce11590f14a5e6