mmi2grpc: Don't reconnect phone on reset
This is a partial revert of d5a38c8db99c538ee4777a34fbc8c6685c7f5503

We don't want and don't need to reconnect the phone on each reset.
Furthermore this is breaking execution of PTS-bot tests with
the error

```
Error: Traceback (most recent call last):
  File "mmi2grpc/__init__.py", line 73, in __enter__
    RootCanal().reconnect_phone()
  File "mmi2grpc/_rootcanal.py", line 128, in reconnect_phone
    if dev_i not in self._parse_phy(devices["Phys"][phy])[1]:
KeyError: 'Phys'
```

Test: TreeHugger
Change-Id: Icf123f8a77cde4e6bc31a02a9582d3f1f63815ae