Fix BluetoothOppIncomingFileActivityTest
File & class name was too long, which caused NoClassDefFoundError

Change-Id: Iab8dec57851735117167675f381b146d7d3191e3
Merged-In: Iab8dec57851735117167675f381b146d7d3191e3
Test: atest BluetoothInstrumentionTests
Bug: 237467631
Tag: #refactor
(cherry picked from commit 1e3d58c96a8c00a18ac1a93c633a19beadd83f6c)